export type Team = { id: string; name: string; short: string }
export const TEAMS_25_26: Team[] = [
  { id: "RMA", name: "Real Madrid", short: "Madrid" },
  { id: "BAR", name: "FC Barcelona", short: "Barça" },
  { id: "ATM", name: "Atlético de Madrid", short: "Atlético" },
  { id: "ATH", name: "Athletic Club", short: "Athletic" },
  { id: "RSO", name: "Real Sociedad", short: "R. Sociedad" },
  { id: "BET", name: "Real Betis", short: "Betis" },
  { id: "VIL", name: "Villarreal CF", short: "Villarreal" },
  { id: "VAL", name: "Valencia CF", short: "Valencia" },
  { id: "SEV", name: "Sevilla FC", short: "Sevilla" },
  { id: "CEL", name: "RC Celta", short: "Celta" },
  { id: "OSA", name: "CA Osasuna", short: "Osasuna" },
  { id: "GET", name: "Getafe CF", short: "Getafe" },
  { id: "GIR", name: "Girona FC", short: "Girona" },
  { id: "RAY", name: "Rayo Vallecano", short: "Rayo" },
  { id: "MAL", name: "RCD Mallorca", short: "Mallorca" },
  { id: "ESP", name: "RCD Espanyol", short: "Espanyol" },
  { id: "ALA", name: "Deportivo Alavés", short: "Alavés" },
  { id: "LEV", name: "Levante UD", short: "Levante" },
  { id: "ELC", name: "Elche CF", short: "Elche" },
  { id: "ROV", name: "Real Oviedo", short: "Oviedo" },
]
