export const TEAMS_25_26 = [
  { id: 'ath', name: 'Athletic Club' },
  { id: 'atl', name: 'Atlético de Madrid' },
  { id: 'osa', name: 'CA Osasuna' },
  { id: 'cel', name: 'RC Celta' },
  { id: 'ala', name: 'Deportivo Alavés' },
  { id: 'elc', name: 'Elche CF' },
  { id: 'fcb', name: 'FC Barcelona' },
  { id: 'get', name: 'Getafe CF' },
  { id: 'gir', name: 'Girona FC' },
  { id: 'lev', name: 'Levante UD' },
  { id: 'ray', name: 'Rayo Vallecano' },
  { id: 'esp', name: 'RCD Espanyol' },
  { id: 'mal', name: 'RCD Mallorca' },
  { id: 'bet', name: 'Real Betis' },
  { id: 'rma', name: 'Real Madrid' },
  { id: 'ove', name: 'Real Oviedo' },
  { id: 'rso', name: 'Real Sociedad' },
  { id: 'sev', name: 'Sevilla FC' },
  { id: 'val', name: 'Valencia CF' },
  { id: 'vil', name: 'Villarreal CF' },
]
